spring:
  application:
    name: HRBank-team1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{PGDATABASE}}
  #    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  #    username: ${USER_NAME}
  #    password: ${USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#  h2:
#    console:
#      enabled: true

schedule:
  backup-cron: "0 0 0/1 * * *"

hrBank:
  repository:
    file-directory: files
